# Generated by Django 2.1.7 on 2019-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0004_auto_20190217_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
